import {Antivirus} from "../models/Antivirus";
import '../App.css'

export const antivirusList : Antivirus[] = [
    new Antivirus(1, 'Kaspersky', 'Kaspersky Lab', 'Kaspersky is a well-known antivirus software', true, new Date('2020-01-01')),
    new Antivirus(2, 'Bitdefender', 'Bitdefender', 'Bitdefender is a romanian antivirus.', true, new Date('2001-11-06')),
    new Antivirus(3, 'Avast', 'Avast Software', 'Avast is a czech antivirus software', true, new Date('2010-10-10')),
    new Antivirus(4, 'Norton', 'NortonLifeLock', 'Norton is an antivirus software', true, new Date('2016-01-01')),
    new Antivirus(5, 'McAfee', 'McAfee', 'McAfee is an antivirus software', true, new Date('2006-01-01')),
    new Antivirus(6, 'ESET', 'ESET', 'ESET is an antivirus software', true, new Date('2017-01-01')),
    new Antivirus(7, 'SuperAntiSpyware', 'SuperAntiSpyware', 'SuperAntiSpyware is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(8, 'Malwarebytes', 'Malwarebytes', 'Malwarebytes is an antivirus software', true, new Date('2018-01-01')),
    new Antivirus(9, 'Spybot', 'Safer-Networking', 'Spybot is an antivirus software', false, new Date('2002-01-01')),
    new Antivirus(10, 'Windows Defender', 'Microsoft', 'Windows Defender is an antivirus software', true, new Date('2015-01-01')),
    new Antivirus(11, 'Avira', 'Avira', 'Avira is an antivirus software', true, new Date('2019-01-01')),
    new Antivirus(12, 'Panda', 'Panda Security', 'Panda is an antivirus software', true, new Date('2011-01-01')),
    new Antivirus(13, 'AVG', 'AVG Technologies', 'AVG is an antivirus software', true, new Date('2008-01-01')),
    new Antivirus(14, 'WhatAVirus', 'WhatAVirus', 'WhatAVirus is an antivirus software', false, new Date('2017-01-01')),
    new Antivirus(15, 'VirusDestroyer', 'VirusDestroyer', 'VirusDestroyer is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(16, 'AntivirusX', 'AntivirusX', 'AntivirusX is an antivirus software', false, new Date('2000-06-01')),
    new Antivirus(17, 'AntivirusY', 'AntivirusY', 'AntivirusY is an antivirus software', false, new Date('2000-01-02')),
    new Antivirus(18, 'AntivirusZ', 'AntivirusZ', 'AntivirusZ is an antivirus software', false, new Date('2014-03-06')),
    new Antivirus(19, 'BestAntivirus', 'BestAntivirus', 'BestAntivirus is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(20, 'WorstAntivirus', 'WorstAntivirus', 'WorstAntivirus is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(21, 'Antivirus2000', 'Antivirus2000', 'Antivirus2000 is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(22, 'Antivirus2001', 'Antivirus2001', 'Antivirus2001 is an antivirus software', false, new Date('2001-01-01')),
    new Antivirus(23, 'Antivirus2002', 'Antivirus2002', 'Antivirus2002 is an antivirus software', false, new Date('2002-01-01')),
    new Antivirus(24, 'Antivirus2003', 'Antivirus2003', 'Antivirus2003 is an antivirus software', false, new Date('2003-01-01')),
    new Antivirus(25, 'FlowerAntivirus', 'FlowerAntivirus', 'FlowerAntivirus is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(26, 'Antivirus2020', 'Antivirus2020', 'Antivirus2020 is an antivirus software', false, new Date('2020-01-01')),
    new Antivirus(27, 'HarmlessAntivirus', 'HarmlessAntivirus', 'HarmlessAntivirus is an antivirus software', false, new Date('2000-01-01')),
    new Antivirus(28, 'MyAntivirus', 'MyAntivirus', 'MyAntivirus is an antivirus software', false, new Date('2000-01-01')),
]
